### DISCUSSION TITLE
Using menu not as a dropdown

### DISCUSSION THREAD

**Discussion by violabg** [chakra-ui/chakra-ui#2923] [Q&A]
I’m wondering if there is a simple way to use the menu component not as a dropdown button, but as a sidebar menu for example.
I’ve tried to add the property isOpen to it, but the problem is that it creates a wrapper div around the MenuList with position: absolute style, and there is not an easy way to set it to position: relative.
I had to create a css file to make it work.

```css
.parentClass > div {
   position: relative !important
}
```
