### DISCUSSION TITLE
Missing styles in print mode.

### DISCUSSION THREAD

**Discussion by malashevskyi** [chakra-ui/chakra-ui#3577] [Ideas]
I made myself a chakra-ui cheatsheet with default colors, sizes, spaces, icons. Then I was going to print it and I saw the following:
![](https://i.imgur.com/ENlesuZ.png)

---
Then I went to chakra-ui.com, and I saw the same situation:
![](https://i.imgur.com/RZglJQ1.png)

---
I added the property:
```css
body {
  -webkit-print-color-adjust: exact;
}
```
and everything shows correctly. I think that it should be by default.
