### DISCUSSION TITLE
use breakpoints in emotion styled?

### DISCUSSION THREAD

**Discussion by ilchenkoArtem** [chakra-ui/chakra-ui#5231] [Q&A]
Hello. Can i use brealpoint in emotion styled? 

Smth:
```js
export const Wrapper = styled('div')(({theme}) => `
  position: sticky;
  top: 0;
  padding: red;
  border-right: 1px solid red;
  height: 100vh;
  max-width: 200px;
  
  ${theme.breakpoints.sm} {
    color: red;
  }
`);
```

Expected Result: 

```css
{
  position: sticky;
  top: 0;
  padding: red;
  border-right: 1px solid red;
  height: 100vh;
  max-width: 200px;
  
  @media screen and (min-width: 30em)  {
    color: red;
  }
}
```
