### DISCUSSION TITLE
Move Modal to the Left

### DISCUSSION THREAD

**Discussion by arthurgailes** [chakra-ui/chakra-ui#6132] [Q&A] [answered]
Hello,

I'd like to move my modal to the left side of my screen, but there doesn't appear to be a parallel to margin-top in the CSS properties. Is there any way to do this?

Thank you!

**Comment by hugobqd** [comment, marked as answer]
There are no props to left-align a Modal, because in UI standards, modals are always centered horizontally.

However, you can use regular CSS to modify layout: 
```css
.chakra-modal__content-container {
    justify-content: flex-start;
    padding-inline: 2rem;
}
```
