### DISCUSSION TITLE
Chain animations

### DISCUSSION THREAD

**Discussion by ivan-kleshnin** [chakra-ui/chakra-ui#6669] [Q&A]
Hi there. I have a CSS with 2 chained/sequential animations which I want to rewrite in conventional Chakra-UI syntax.

### Inputs

```css
.animation {
  animation: moveLeft, moveLeft2;
  animation-duration: 1s, 1s;
  animation-fill-mode: both, forwards;
  animation-delay: 0s, 2s;
  animation-iteration-count: 1, 1;
}

@keyframes moveLeft {
  from {
    ...
  }
  to {
    ...
  }
}

@keyframes moveLeft2 {
  from {
    ...
  }
  to {
    ...
  }
}
```

The above translates to the following:

```tsx
const moveLeft = keyframes`
  from {
    opacity: 0;
    transform: translate(0px, 0px);
  }
  to {
    opacity: 1;
    transform: translate(-100px, 0px);
  }
`

const moveLeft2 = keyframes`
   from {
    opacity: 1;
    transform: translate(-100px, 0px);
  }
  to {
    opacity: 0;
    transform: translate(-200px, 0px);
  }

const animation = `${moveLeft} 1s linear 0s 1 both, ${moveLeft2} 1s linear 2s 1 forwards`;

<Box
  animation={animation}
/>
```

### Question

Is there a way to split the line below?

```tsx
const animation = `${moveLeft} 1s linear 0s 1 both, ${moveLeft2} 1s linear 2s 1 forwards`;
```

It's very unclear with position-based approach. I would really prefer to have something like this:

```css
.animation {
  animation: moveLeft, moveLeft2;
  animation-duration: 1s, 1s;
  animation-fill-mode: both, forwards;
  animation-delay: 0s, 2s;
  animation-iteration-count: 1, 1;
}
```

```tsx
// NOT SUPPORTED
<Box
  animationName={["moveLeft", "moveLeft2"]}
  animationDuration={["1s", "1s"]}
/>
```

or even better:

```tsx
// NOT SUPPORTED
<Box
  animations={[
    {name: "moveLeft", duration: "1s", ...},
    {name: "moveLeft2", duration: "1s", ...},
  ]}
/>
```

It's likely not hard to write a translator from one syntax to another on my side but maybe something like that is already supported?!
