### DISCUSSION TITLE
Semantic Tokens for Custom Font & Font Weight

### DISCUSSION THREAD

**Discussion by sh-sam** [chakra-ui/chakra-ui#6788] [General]
I am trying to define a font system with font-weights `100` thru `900`

The problem is, I have multiple font files which represent a given weight i.e:

`MyFontRegular.ttf`
`MyFontBold.ttf`
`MyFontExtraBold.ttf`

Thus, I can't use have a blanket definition in my theme like so:

```
import { extendTheme } from '@chakra-ui/react';

export const fonts = extendTheme({
  body    : 'MyFontRegular, sans-serif',
  heading : 'MyFontRegular, sans-serif',
});
```

I figured I could use `semanticTokens` to do something like this:

```
const tokens = extendTheme({
  semanticTokens: {
    textStyles: {
      extraBold: 'MyFontExtraBold',
    },
  },
});
```

But this just results in `fontFamily: extraBold`

Is it possible to use tokens to define something like this, or am I thinking of this the wrong way?

**Comment by mrmartineau** [comment]
It seems to me that you need to define those fonts properly (using the `@font-face` rule) so that they have the same `font-family` value: `'MyFont'` and specific font-weights:

e.g.

```css
@font-face {
  font-family: 'MyFont';
  src: url('MyFontRegular.ttf') format('truetype');
  font-display: 'swap';
  font-weight: 400;
}
@font-face {
  font-family: 'MyFont';
  src: url('MyFontBold.ttf') format('truetype');
  font-display: 'swap';
  font-weight: 600;
}
@font-face {
  font-family: 'MyFont';
  src: url('MyFontExtraBold.ttf') format('truetype');
  font-display: 'swap';
  font-weight: 900;
}
```

Then when you come to use them you would specify the font and font-weight:

```jsx
<Text fontFamily="body" fontWeight="600">Some text</Text>
```
