### DISCUSSION TITLE
Is there an easy way to use @supports feature query via Chakra?

### DISCUSSION THREAD

**Discussion by Southclaws** [chakra-ui/chakra-ui#7362] [Q&A]
Hey all! I'm building a site with a huge focus on accessibility and progressive enhancement.

My designs are also using some newer features, like backdrop-filter blur (it looks sexy as hell, you cannot deny this) and I want to provide a graceful degradation fallback for this on older browsers that do not support the backdrop blurring effect.

Now I could write some custom CSS and target my chakra component via a manually written class name but is there a way for Chakra to do this already? Effectively, I would like to use:

```css
@supports ( (-webkit-backdrop-filter: none) or (backdrop-filter: none) ) {
  .fallback__backdrop-blur {
    background-color: rgba(255, 255, 255, .6);
    -webkit-backdrop-filter: blur(1.5em);
    backdrop-filter: blur(1.5em);
  }
}
```
