### ISSUE TITLE
[Box] Merge/Overwrite systemProps with extraConfig

### ISSUE THREAD

**Issue by xtalx** [chakra-ui/chakra-ui#119]
I noticed some duplicate/invalid css properties with the box component. The problem props are as follows.

- bgSize
- bgRepeat
- overflowX
- overflowY

To illustrate the issue create a Box like so

```jsx
    <Box overflowY="scroll" overflowX="scroll" bgSize="200px" bgRepeat="repeat">
      hi
    </Box>
```

The resulting css:

```css
.css-1uieup {
    overflow-y: scroll;
    overflow-x: scroll;
    bg-size: 200px;
    bg-repeat: repeat;
    overflow-y: scroll;
    overflow-x: scroll;
    background-size: 200px;
    background-repeat: repeat;
}
```
I believe one way to fix it is to remove extraConfig from the function call and add it to the compose function. That way anything defined in config that matches what's in Styled System will overwrite the Styled System. 

After making that change all of the components I tested worked properly.
