### ISSUE TITLE
[Theme/GlobalStyle API] Any supposedly global style gets scoped to body

### ISSUE THREAD

**Issue by ljosberinn** [chakra-ui/chakra-ui#1561]
According to the examples in the [docs](https://next.chakra-ui.com/docs/global-styles#how-it-works), changing `theme.styles.global` applies global CSS.

However, using said snippets produces the following CSS in both cases:

```css
body html, body body {
  color: #4A5568;
  font-size: 0.875rem;
  line-height: 1.625;
}
```

Furthermore, to be able to apply styles with `-` in their key such as `background-color`, `backgroundColor` does not work, leading to this CSS:
```js
const myTheme = {
  ...theme,
  styles: {
    global: {
      '#__next': {
        backgroundColor: 'pink',
        height: '100%',
        width: '100%',
      },
    },
  },
};
```

```css
body #__next backgroundColor {
  50: #FFF5F7;
  100: #FED7E2;
  200: #FBB6CE;
  300: #F687B3;
  400: #ED64A6;
  500: #D53F8C;
  600: #B83280;
  700: #97266D;
  800: #702459;
  900: #521B41;
}
```

However: 

```js
const myTheme = {
  ...theme,
  styles: {
    global: {
      '#__next': {
        'background-color': 'pink',
        height: '100%',
        width: '100%',
      },
    },
  },
};
```
```css
body #__next{
  background-color:pink;
  height:100%;
  width:100%;
}
```

works! But `emotion` will console.error:

![image](https://user-images.githubusercontent.com/29307652/89711220-230ca680-d989-11ea-8203-d07a9310cea8.png)

Reproduction: https://codesandbox.io/s/cocky-gagarin-o0oku?file=/src/App.tsx

More convo: https://canary.discordapp.com/channels/660863154703695893/660865137137156146/741635330301755493
