### ISSUE TITLE
[Input] When type="date", Calendar icon color stays black in Dark Mode

### ISSUE THREAD

**Issue by markjackson02** [chakra-ui/chakra-ui#1786]
**Current Behavior**

In dark mode, the calendar input icon remains black:

![image](https://user-images.githubusercontent.com/35121685/90967624-cc868880-e4af-11ea-866c-5e1f6329dc3a.png)
![image](https://user-images.githubusercontent.com/35121685/90967615-a95bd900-e4af-11ea-9f2c-a3a7e574c2d6.png)

**Expected Behavior** 

The calendar icon should turn white.

**Link to minimal reproduction** 

https://codesandbox.io/s/chakra-ui-date-input-calendar-icon-bug-v14dv

**Comment by segunadebayo** [comment]
Hi @markjackson02, this isn't an issue from Chakra. I'll recommend you style the calendar icon yourself using `useColorMode` and emotion's `css` prop if you need to.

Happy to explain a bit more if it's not clear.

Cheers

**Comment by markjackson02** [comment]
Yes, this did the trick:
```
                <Input
                    type="date"
                    css={css`
                        ::-webkit-calendar-picker-indicator {
                            background: url(https://cdn3.iconfinder.com/data/icons/linecons-free-vector-icons-pack/32/calendar-16.png) center/80% no-repeat;
                            color: black;
                        }
                    `}
                />
```
Thank you @bgopikrishna and super thank you to @segunadebayo for this amazing framework!

**Comment by ekhiw** [comment]
I was looking for this, i just have same problem,
and i tweak above solution, i use Input component variant, and add this to my variant
```css
::-webkit-calendar-picker-indicator" : {
 bg: "rgba(0,0,0,0)",
 bottom: 0,
 color: "rgba(0,0,0,0)",
 cursor: "pointer",
 height: "auto",
 left: 0,
 position: "absolute",
 right: 0,
 top: 0,
 width: "auto",
}
```

then just set variant to use it

```javascript
<FormControl>
 <FormLabel>Date</FormLabel>
  <InputGroup>
     <Input
       type="date"
       placeholder="Input date"
       variant={"my-variant"}
       {...field}/>
     <InputRightElement
        children={<CalendarIcon color='white' />}
      />
  </InputGroup>
  <FormErrorMessage>{error?.message}</FormErrorMessage>
 </FormControl>
```

**Comment by priyam-verma** [comment]
`.date-class::-webkit-calendar-picker-indicator {
    filter: invert(1);
}`

**Comment by valerii15298** [comment]
Even better to use :
```css
input {
  color-scheme: dark;
}
```
