### ISSUE TITLE
Margin not working in Stack Component's Children

### ISSUE THREAD

**Issue by anubra266** [chakra-ui/chakra-ui#4016]
# 🐛 Bug report

Every Child component of a `Stack` that's not the first child has it's margin overwritten by some strange negation selector,

## 💥 Steps to reproduce

1. Create a Stack component,
2. Give it some children
3. Give the children a margin
4. Only the margin of the first child is reflected

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/upbeat-sound-zrw2q?file=/src/index.js

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |1.6.1 |
| Browser          | Chrome and Firefox |
| Operating System |Ubuntu|

## 📝 Additional information
Tried in the docs:
![image](https://user-images.githubusercontent.com/30869823/118347779-ae7d1e80-b53d-11eb-8a79-5f1a804b5ced.png)

This is the strange styling
```css
.css-ej5gxm > :not(style) ~ :not(style) {
    margin-top: var(--chakra-space-1);
    -webkit-margin-end: 0px;
    margin-inline-end: 0px;
    margin-bottom: 0px;
    -webkit-margin-start: 0px;
    margin-inline-start: 0px;
}
/* .css-ej5gxm is the Stack's derived class */
```
