### ISSUE TITLE
CSS `inset` does not work with multi-value syntax

### ISSUE THREAD

**Issue by selrond** [chakra-ui/chakra-ui#5191]
### Description

When I use `inset="4px 8px"` on components it produces invalid output.

### Link to Reproduction

https://codesandbox.io/s/chakra-ui-inset-bug-irohn

### Steps to reproduce

See the codesandbox and check out the css output of the `Comp`:

```tsx
<Box position="absolute" inset="4px 8px">
  Hello world!
</Box>
```

produces this css:

```css
.generated-classname {
    position: absolute;
    top: 4px 8px;
    right: 4px 8px;
    bottom: 4px 8px;
    left: 4px 8px;
}
```

According to the [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/inset), it should behave same as `margin`

I've managed to fix it already, just wanted to create an issue first. 
Do you want me to open a PR?

### Chakra UI Version

1.7.2

### Browser

Firefox Developer Edition, Chrome Dev Edition

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux
