### ISSUE TITLE
Remove content shifting when Modal is opened.

### ISSUE THREAD

**Issue by b-novikov-ipersonality** [chakra-ui/chakra-ui#5705]
### Description

When modal is open, scroll bar is removed, shifting content. I suggest to tweak styles to change this behavior 

### Problem Statement/Justification

For me as a user it's unpleasant to see content of a webpage shift. I consider it bad UX because it's kinda pushes away from resource. 

### Proposed Solution or API

Solution found on stackoverflow:

```css
html {
    margin-right: calc(100% - 100vw);
}
body {
    margin-right: calc(100vw - 100%);
}
```
works for me well. But maybe there's a better solution.

### Alternatives

Manually style html and body as per proposed solution.

### Additional Information

https://stackoverflow.com/a/47276144
