### ISSUE TITLE
Recommendations for Date Picker package

### ISSUE THREAD

**Issue by wouterds** [chakra-ui/chakra-ui#580]
Is there any date picker package you would recommend for using in combination with Chakra UI? I absolutely love this lib but am troubled finding a decent date picker package to integrate with.

**Comment by wouterds** [comment]
I ended up using [`react-datepicker`](https://github.com/Hacker0x01/react-datepicker/) and styling that myself a bit.

![Screenshot 2020-06-19 at 19 48 45](https://user-images.githubusercontent.com/1210628/85165302-e7e1d700-b265-11ea-8e0b-92845a0f70a0.jpg)

**Comment by segunadebayo** [comment]
Thanks for coming back to share your solution @wouterds.

Cheers.

**Comment by cbioley** [comment]
@wouterds Would you mind sharing your styles? 🤓

**Comment by wouterds** [comment]
> @wouterds Would you mind sharing your styles? 🤓

```css
.react-datepicker {
  font-family: -apple-system, system-ui, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', sans-serif;
  overflow: hidden;
}

.react-datepicker__navigation--next--with-time:not(.react-datepicker__navigation--next--with-today-button) {
  right: 90px;
}

.react-datepicker__navigation--previous,
.react-datepicker__navigation--next {
  height: 8px;
}

.react-datepicker__navigation--previous {
  border-right-color: #cbd5e0;
  &:hover {
    border-right-color: #a0aec0;
  }
}

.react-datepicker__navigation--next {
  border-left-color: #cbd5e0;

  &:hover {
    border-left-color: #a0aec0;
  }
}

.react-datepicker-wrapper,
.react-datepicker__input-container {
  display: block;
}

.react-datepicker__header {
  border-radius: 0;
  background: #f7fafc;
}

.react-datepicker,
.react-datepicker__header,
.react-datepicker__time-container {
  border-color: #e2e8f0;
}

.react-datepicker__current-month,
.react-datepicker-time__header,
.react-datepicker-year-header {
  font-size: inherit;
  font-weight: 600;
}

.react-datepicker__time-container .react-datepicker__time .react-datepicker__time-box ul.react-datepicker__time-list li.react-datepicker__time-list-item {
  margin: 0 1px 0 0;
  height: auto;
  padding: 7px 10px;

  &:hover {
    background: #edf2f7;
  }
}

.react-datepicker__day:hover {
  background: #edf2f7;
}

.react-datepicker__day--selected,
.react-datepicker__day--in-selecting-range,
.react-datepicker__day--in-range,
.react-datepicker__month-text--selected,
.react-datepicker__month-text--in-selecting-range,
.react-datepicker__month-text--in-range,
.react-datepicker__time-container .react-datepicker__time .react-datepicker__time-box ul.react-datepicker__time-list li.react-datepicker__time-list-item--selected {
  background: #3182ce;
  font-weight: normal;

  &:hover {
    background: #2a69ac;
  }
}
```
