### ISSUE TITLE
DarkMode and LightMode do not affect text color

### ISSUE THREAD

**Issue by a463** [chakra-ui/chakra-ui#6916]
### Description

When I wrap a component with `DarkMode` or `LightMode` the text color is not affected and it changes based on the active theme, rather than the theme forced by the wrapping the component.

### Link to Reproduction

https://codesandbox.io/s/competent-rain-i1sz84

### Steps to reproduce

Try to toggle the theme on the above codesandbox, notice the text color changing even though the component is wrapped with `DarkMode`. Toggling the theme does not affect the background color of the `Box`, which always stays in dark mode, so the hooks are working properly.

### Chakra UI Version

2.3.6

### Browser

Chrome 106, Firefox 106

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by a463** [comment]
Not sure if this is a bug or a CSS limitation, the reason this happens is because `--chakra-colors-chakra-body-text` is not defined on `:root` or `body`, but `[data-theme="dark"]`. The CSS pretty much looks like:

```CSS
[data-theme="dark"] {
  --chakra-colors-chakra-body-text: var(--chakra-colors-whiteAlpha-900);
}

body {
  color: var(--chakra-colors-chakra-body-text);
}
```

The var in the body does not reference `[data-theme="dark"] `, but rather what is defined in `html[data-theme="light"]`.

Anyway there is an easy fix for this, and that is simply adding the color to the first element on
