### ISSUE TITLE
Chakra is overriding global H1...H6, makes it impossible for third party components to work

### ISSUE THREAD

**Issue by androidplayer1** [chakra-ui/chakra-ui#8275]
### Description

![image](https://github.com/chakra-ui/chakra-ui/assets/86848862/c2c1e928-d0fb-4196-8550-5323828ec91e)

### Link to Reproduction

https://google.com

### Steps to reproduce

I am trying to use a markdown editor, but that is not possible due to Chakra intefering/overriding the H1, H2, H3, H4, H5, H6 styling to every element globally.

### Chakra UI Version

Latest

### Operating System

- [X] macOS
- [X] Windows
- [ ] Linux

**Comment by jamesarosen** [comment]
Chakra has many global styles that are impossible to unset:

```css
:where(pre, code, kbd, samp) {
  font-family: SFMono-Regular,Menlo,Monaco,Consolas,monospace;
  font-size: 1em;
}

a {
  background-color: transparent;
  color: inherit;
  text-decoration: inherit;
}

abbr[title] {
  border-bottom: none;
  text-decoration: underline;
  -webkit-text-decoration: underline dotted;
  text-decoration: underline dotted;
}

:where(button, input, optgroup, select, textarea) {
  font-family: inherit;
  font-size: 100%;
  line-height: 1.15;
  margin: 0;
}
```

I find many of these problematic because I want to have some CSS provide defaults. But that's impossible with Chakra. If I try to delete one of these in my theme, Chakra just sees that as empty and deep-merges in its default.
