### ISSUE TITLE
Heading size does not work

### ISSUE THREAD

**Issue by osadasami** [chakra-ui/chakra-ui#829]
So i got heading with that code

```html
<Heading as="h2" size="xs">{title}</Heading>
```

When i change `size` prop nothing happened

In devtools I see that when focusing on my heading

```css
.css-1fgomf8 {
    font-size: sm;
    line-height: shorter;
    font-weight: bold;
    font-family: heading;
}
```

in `font-size` I got `sm` string. Not only is this a non-working option, but it also substitutes even the wrong string
